apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uptimekumahttpmonitors.jetpack.io
spec:
  scope: Namespaced
  group: jetpack.io
  names:
    kind: UptimeKumaHttpMonitor
    plural: uptimekumahttpmonitors
    singular: uptimekumahttpmonitor
    shortNames:
      - ukm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Friendly Name of the Monitor
                interval:
                  type: integer
                  default: 60
                  description: Interval in seconds for the HTTP monitor
                url:
                  type: string
                  description: URL that you want to montior