apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uptimekumahttpmonitors.jetpack.io
spec:
  scope: Namespaced
  group: jetpack.io
  names:
    kind: UptimeKumaHttpMonitor
    plural: uptimekumahttpmonitors
    singular: uptimekumahttpmonitor
    shortNames:
      - ukm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                resendInterval:
                  type: integer
                  default: 0
                upsideDown:
                  type: boolean
                  default: false
                keyword:
                  type: string
                  default: null
                headers:
                  type: string
                  default: null
                body: 
                  type: string
                  default: null
                method:
                  type: string
                  default: "GET"
                accepted_statuscodes:
                  type: array
                  default: [200-299]
                  items:
                    x-kubernetes-int-or-string: true
                ignoreTls:
                  type: boolean
                  default: false
                expiryNotification:
                  type: boolean
                  default: false
                maxredirects:
                  type: integer
                  default: 10
                maxretries:
                  type: integer
                  default: 0
                retryInterval:
                  type: integer
                  default: 60
                  description: Seconds Between retries
                defaultNotifiers:
                  type: boolean
                  default: true
                  description: "Also add the default Notifier for this monitor"
                notifiers:
                  type: array
                  items:
                    type: string
                  description: List of Notifiers to notify
                name:
                  type: string
                  description: Friendly Name of the Monitor
                interval:
                  type: integer
                  default: 60
                  description: Interval in seconds for the HTTP monitor
                url:
                  type: string
                  description: URL that you want to montior