---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-controller
  labels:
    app.kubernetes.io/name: kuma-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kuma-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuma-controller
    spec:
      serviceAccountName: kuma-controller
      containers:
      - name: kuma-controller
        image: harbor.k8s.libraries.psu.edu/library/kuma-operator:latest
        command:
        - sleep
        - infinity
