apiVersion: jetpack.io/v1alpha1
kind: UptimeKumaHttpMonitor
metadata:
  name: sample-three
spec:
  keyword: Penn
  expiryNotification: true
  maxretries: 2
  retryInterval: 20
  defaultNotifiers: true
  notifiers:
  - ntfy
  url: https://psu.edu
  interval: 90
  name: 'Penn State'
