apiVersion: jetpack.io/v1alpha1
kind: UptimeKumaHttpMonitor
metadata:
  name: sample
spec:
  expiryNotification: true
  maxretries: 2
  retryInterval: 20
  defaultNotifiers: true
  notifiers:
  - ntfy
  url: https://google.com
  interval: 20
  name: 'Google'
